"""empty message

Revision ID: 30baf16d7785
Revises: 354186160a21
Create Date: 2024-01-17 20:20:46.817580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30baf16d7785'
down_revision = '354186160a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('telephone', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('profile_img', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('post', sa.String(length=2000), nullable=False),
    sa.Column('date_post', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('min_followers', sa.Integer(), nullable=True),
    sa.Column('duration_in_weeks', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('industry', sa.String(length=20), nullable=True),
    sa.Column('id_company', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_company'], ['users_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_network', sa.String(), nullable=False),
    sa.Column('social_network_url', sa.String(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('id_influencer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_influencer'], ['users_influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_influencer', sa.String(), nullable=False),
    sa.Column('cover_letter', sa.String(length=500), nullable=False),
    sa.Column('social_network_url', sa.String(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('id_offer', sa.Integer(), nullable=True),
    sa.Column('id_influencer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_influencer'], ['users_influencers.id'], ),
    sa.ForeignKeyConstraint(['id_offer'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_networks', sa.String(), nullable=False))
        batch_op.drop_column('social_media')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_media', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('social_networks')

    op.drop_table('offers_candidates')
    op.drop_table('social_networks')
    op.drop_table('offers')
    op.drop_table('users_company')
    # ### end Alembic commands ###
