"""empty message

Revision ID: 354186160a21
Revises: c81c957b8e7e
Create Date: 2024-01-17 19:43:44.674988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354186160a21'
down_revision = 'c81c957b8e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('date_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('profile_img', sa.String(), nullable=False),
    sa.Column('headline', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('social_media', sa.String(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_influencer', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_influencer')

    op.drop_table('users_influencers')
    # ### end Alembic commands ###
