"""empty message

Revision ID: 4f0f710f3cb6
Revises: fee98b586a96
Create Date: 2024-01-26 20:18:05.316266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f0f710f3cb6'
down_revision = 'fee98b586a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('offerscandidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_candidate', sa.Enum('pending', 'accepted', 'refused', name='status'), nullable=False))
        batch_op.drop_column('status')

    with op.batch_alter_table('userscompany', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userscompany', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('offerscandidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('opened', 'cancelled', 'closed', name='status'), autoincrement=False, nullable=False))
        batch_op.drop_column('status_candidate')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.alter_column('industry',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
