"""empty message

Revision ID: 82d76ac82780
Revises: 8637691c68d7
Create Date: 2024-01-25 10:22:00.478418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d76ac82780'
down_revision = '8637691c68d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userscompany', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               nullable=True)
        batch_op.alter_column('cif',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('telephone',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('headline',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('userscompany_cif_key', type_='unique')

    with op.batch_alter_table('usersinfluencers', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('date_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('telephone',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('headline',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('social_networks',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersinfluencers', schema=None) as batch_op:
        batch_op.alter_column('social_networks',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('headline',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('telephone',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('userscompany', schema=None) as batch_op:
        batch_op.create_unique_constraint('userscompany_cif_key', ['cif'])
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('headline',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('telephone',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cif',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
