"""empty message

Revision ID: fee98b586a96
Revises: cbcbb9871018
Create Date: 2024-01-25 07:47:29.423599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee98b586a96'
down_revision = 'cbcbb9871018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userscompany', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('cif', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('headline', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userscompany', schema=None) as batch_op:
        batch_op.drop_column('headline')
        batch_op.drop_column('telephone')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('country')
        batch_op.drop_column('cif')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
